# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 17 Pro Max",
#   "iPad Pro 13-inch (M5)"
 ])

 languages([
    "en-US",
    "de-DE",
    "fi"
 ])

# The name of the scheme which contains the UI Tests
scheme("nightguard")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Ensure simulator GUI is visible (not headless)
headless(false)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
